
:hardbreaks:
= WIS2 Notification Message Format

As explained in https://community.wmo.int/wis2-topic-hierarchy:
-----
WIS 2.0 real-time data sharing is based on a message queuing protocol (MQP) supporting a publication/subscription mechanism. A user can subscribe to an MQP broker to receive real-time notifications that some data can be downloaded. The notification message received from the MQP broker contains a URL to download the data. In addition, the MQP broker offers a range of topics organised in a hierarchy. The users can select their topics of interest and subscribe to them to receive notifications and download data relevant to their work.
-----

The standard notification message format ensures that the WIS2 ecosystem (data publisher, data user, and global services) is a robust, effective, and unified data exchange platform for weather, climate, and water.

[id=geojson]
. Use of GeoJSON
+

Having message in GeoJSON format will, for example, allow the use of standard validators such as link:https://geojson.io/#map=2/20.0/0.0[geojson.io] or link:https://www.itb.ec.europa.eu/json/geojson/upload[europa.eu] to check the correctness of the format.

. A complete example
+

[indent=10]
----
{
"id": "31e9d66a-cd83-4174-9429-b932f1abe1be",
"version": "v04",
"type": "Feature",
"geometry": {
    "type": "Point",
    "coordinates": [
        6.146255135536194,
        46.223296618227444
    ]
},
"properties": {
    "pubtime": "20220320T045018.314854383Z",
    "datetime": "20220320T044500Z",
    "integrity": {
        "method": "sha512",
        "value": "A2KNxvks...S8qfSCw=="
    },
    "data_id": "wis2/CAN/eccc-msc/data/core/weather/surface-based-obs/landFixed/UANT01_CWAO_200445___15103.bufr4",
    "content": {
        "encoding": "utf-8",
        "value": "encoded bytes from the file",
        "length": 457
    }
},
"links": [
    {
        "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
        "rel": "canonical",
        "type": "application/x-bufr"
    }
    ]
}
----

. Description of the format

.The message format
[cols="1,1,1,1,2"]
|===
| Key | Value(s) | Example | Status | Description

|*id*
|UUID
|`31e9d66a-cd83-4174-9429-b932f1abe1be`
|Mandatory
|A unique identifier of the message using the UUID standard (RFC 4122). The identifier is generated by the originator of the *message*.
It provides the anti-loop feature that is needed to ensure that the message will be seen *once* by all Global Brokers.
It remains the same throughout the lifetime of the message in WIS2 ecosystem.
|*version*
|v04
|`v04`
|Mandatory
|This is the version 4 of the message format.
|*type*
|Feature
|`Feature`
|Mandatory
|The type feature is mandatory in the WIS2 message format.
|*geometry*
|Point \| Polygon \| null
|`Point`
|Mandatory
|RFC 7946 defines 7 types of geometry: "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon", and "GeometryCollection".
It has been decided to restrict those types to only two: `Point` and `Polygon`.
It must be noted that the *geometry* key is mandatory in GeoJSON but can be of type `null` +

|*properties*
|Array
|`{
    "pubtime": "2022-03-20T04:50:18.314854383Z",
    "datetime": "2022-03-20T04:45:00Z",
    "integrity": {
        "method": "sha512",
        "value": "A2KNxvks...S8qfSCw=="
    },
    "data_id": "wis2/CAN/eccc-msc/data/core/weather/surface-based-obs/landFixed/UANT01_CWAO_200445___15103.bufr4",
    "content": {
        "encoding": "utf-8",
        "value": "encoded bytes from the file",
        "length": 457
    }
}`
|Mandatory
|The _Properties_ table describes more precisely the data that is announced through the message. 
|*links*
|Array
|`{
        "href": "https://meteofrance.com/data/nwp/92c557ef-d28e-4713-91af-2e2e7be6f8ab.grib",
        "rel": "canonical",
        "type": "application/x-grib2"
    }`
|Mandatory
|The _links_ table describes more precisely the methods to download the data. 
|===

[id=Examples]

*Examples of geometry*

* _Example 1: Point_
+

[indent=10]
----
"geometry": {
    "type": "Point",
    "coordinates": [
        6.146255135536194,
        46.223296618227444
    ]
}
----

* _Example 2: Point_ with elevation
+

[indent=10]
----
"geometry": {
    "type": "Point",
    "coordinates": [
        6.146255135536194,
        46.223296618227444,
        392
    ]
}
----

* _Example 3: Polygon_
+
[indent=10]
----
"geometry": {
    "type": "Polygon",
    "coordinates": [
    [
      [-7.75,40.43],
      [-7.75,78.46],
      [71.91,78.46],
      [71.91,40.43],
      [-7.75,40.43]
    ]
  ]
}
----

* _Example 3: null_
+
[indent=10]
----
"geometry": null
----

[id=Properties]

**Properties**

.Details of the *properties* array
[cols="1,1,1,1,2"]
|===
| Key | Value(s) | Example | Status | Description

|*pubtime*
|Date/Time in RFC 3339 format. 
|`2022-03-20T04:50:18.314854383Z`
|Mandatory
|Identifies the date/time of when the file was posted/published, in RFC3339 format. The publication date/time is critical for subscribers to prevent message loss by knowing their lag (how far behind the publisher they are). Only Z time zone is accepted.
|*data_id*
|element of the topic tree and unique identifier
|`wis2/CAN/eccc-msc/data/core/weather/surface-based-obs/landFixed/UANT01_CWAO_200445___15103.bufr4`
|Mandatory
|Uniquely identifies the data. It is formed of two parts: +
1. MQTT topic hierarchy where this message will be published as defined in https://community.wmo.int/wis2-topic-hierarchy without leading channel/version + 
2. a unique identifier of the data. It can be the filename used by the originating center or a unique UUID (RFC 4122) or anything chosen 
by the originating center as long as it is unique over a 1 week period.
|*datetime*
|Date/Time in RFC 3339 format 
|`2022-03-20T04:50:18`
|Optional (and exclusive of start_ and end_datetime)
|Identifies the date/time of the data being published, in RFC3339 format. E.g. for observation data, date of measurement. Only Z time zone is accepted.
|*start_datetime*
|Date/Time in RFC 3339 format 
|`2022-03-20T04:50:18`
|Optional (and exclusive of datetime). +
Mandatory if end_datetime is included.
|Identifies the start date/time of the data being published, in RFC3339 format. E.g., for NWP product, start of the forecasting period. Only Z time zone is accepted.
|*end_datetime*
|Date/Time in RFC 3339 format 
|`2022-03-20T04:50:18`
|Optional (and exclusive of datetime). +
Mandatory if start_datetime is included.
|Identifies the end date/time of the data being published, in RFC3339 format. E.g., for NWP product, end of the forecasting period. Only Z time zone is accepted.
|*integrity*
|Array
|`{
        "method": "sha512",
        "value": "A2KNxvks...S8qfSCw=="
    }`
|Optional

|*content*
|Array
|`{
        "encoding": "utf-8",
        "value": "encoded bytes from the file",
        "length": 457
    }`
|Optional
|
|===


[id=Integrity]
*Integrity*
It is _suggested_ (but not mandatory) to include in the message properties integrity information. Providing the information will allow data consumers having accessed the data, that it hasn't been corrupted during the download.

.Detail of the *integrity* array
[cols="1,1,1,1,2"]
|===
| Key | Value(s) | Example | Status | Description

|*method*
|sha512 \| md5 
|`sha512`
|Mandatory
|A format of the hashing method used to enable integrity check of the data. sha512 is the preferred option. md5 can be used as a fallback.
|*value*
|String 
|`3bb12eda3c298db5de25597f54d924f2e17e78a26ad89...b0124ecb8a`
|Mandatory
|The result of the hashing method.
|===

[id=Content]
*Content*
It is _possible_ (but not mandatory) to include in the message the data. For small size data *(less than 2048 bytes)* it can be effective to provide the data as part of the message. Even in that case, the _links_ must be provided. 

.Detail of the *content* array
[cols="1,1,1,1,2"]
|===
| Key | Value(s) | Example | Status | Description

|*encoding*
|utf-8
|`utf-8`
|Mandatory
|If provided the data MUST be encoded in UTF-8.
|*value*
|String 
|`encoded bytes from the file`
|Mandatory
|The UTF-8 version of the data. 
|*length*
|Int (*MUST* be below 2048)
|`1056`
|Mandatory
|The length of the data encoded in UTF-8. The value MUST be below 2048. Global Brokers might discard messages with *length* above 2048 bytes.
|===

[id=links]
*Links*
The _links_ array includes one or more URLs to give access to data.

.Detail of the *links* array
[cols="1,1,1,1,2"]
|===
| Key | Value(s) | Example | Status | Description

|*href*
|URL
|`https://example.com/data/92c557ef-d28e-4713-91af-2e2e7be6f8ab.txt`
|Mandatory
|The link to access the data. The URL *MUST* start with one of the approved downloading protocol preferably HTTPS or SFTP, note that HTTP and FTP are usable but deprecated.
|*rel*
|canonical 
|`canonical`
|Optional
|The UTF-8 version of the data. 
|*type*
|Mime-Type (RFC 6838)
|`application/x-grib`
|Mandatory
|The MIME type of the data.
|===

