== Overview

=== Purpose

This document is intended to define Key Performance Indicators (KPIs) in
support of the WIS2 Notification Message (WNM). KPIs provide measurable
and valuable quality assessment rules over and above the rulesets put
forth by WNM.

The core driver of WNM KPIs is continuous improvement and useability of
notificaiton messages as part of the WMO Information System (WIS).footnote:[https://community.wmo.int/activity-areas/wmo-information-system-wis]

=== Scope

This document is bound to the WNM specification and codelists. All
other metadata specifications or representations are not in scope.

=== Audience

The target stakeholder audiences for this document include (but are not limited to):

* WIS2 Global Services
* WIS2 Nodes
* WIS2 Global Discovery Catalogues (GDCs)
* WIS2 Monitoring

=== How to use

The KPIs in this document are designed to help data providers in the
production of notificaiton messages, as well as WIS2 Global Services, Monitoring and Nodes to measure the quality
of notifications from data providers.

In order to improve quality:

* providers should use the KPIs to build into their notification message generation
* WIS2 Global Services, Monitoring and Nodes should use the KPIs in order to quality assess notification metadata
  and provide subsequent feedback to providers

=== Scoring

Each KPI assesses a number of criteria asssociated with notification message quality,
resulting in a raw score, as well as a percentage. This approach supports
weighted rubric scoring.

=== Reference implementation

The TT-WISMD maintains pywis-pubsubfootnote:[https://github.com/wmo-im/pywis-pubsub], as the
reference WNM validation utility which includes:

* validation against WNM, Annex A: Conformance Class Abstract Test Suite (Normative)
* validation against the KPIs described in this document

Documentation on installation, configuration and usage can be found on the
pywis-pubsub website.

pywis-pubsub is provided as a resource to the community, under continuous
improvement. Contributions are welcome and can be facilited by the
WMO Task Team on WIS Metadata.

=== Conventions

==== Symbols and abbreviated terms

.Symbols and abbreviated terms
|===
|Abbreviation |Term

|DCPC
|Data Collection and Production Centres

|GDC
|Global Discovery Catalogue

|HTML
|Hypertext Markup Language

|HTTP
|Hypertext Transfer Protocol

|HTTPS
|Hypertext Transfer Protocol Secure

|JSON
|JavaScript Object Notation

|MIME
|Multipurpose Internet Mail Extensions

|NC
|National Centre

|OGC
|Open Geospatial Consortium

|pywis-pubsub
|WMO implementation of WNM validation

|URL
|Uniform Resource Locator

|WDC
|World Data Centre

|WIS
|WMO Information System

|WMO
|World Meteorological Organization

|===

