== The WIS2 Notification Message Encoding

A WIS2 Notification Message provides descriptive information about a data made available
through WIS 2.0.

=== Conformance Class Core

==== Overview

This Core Conformance Class provides requirements to articulate the required elements of a WIS2 Notification Message.

include::../requirements/requirements_class_core.adoc[]

The standard notification message format ensures that the WIS2 ecosystem (data publisher, data user, and global services) is a robust, effective, and unified data exchange platform for weather, climate, and water.

==== Message size

The WIS2 Notification Message allows for transmission of messages in a compacted or minified manner, and includes the ability to embedding content inline as required (see <<Content>>).

include::../requirements/core/REQ_message_size.adoc[]

==== GeoJSON compliance

The WIS2 Notification Message schema is based on _GeoJSON_ (RFC7946) and its associated information model.  Compliant messages are therefore compliant with _GeoJSON_.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

A universally unique identifier of the message using the UUID standard (RFC4122). The identifier is generated by the originator of the message.
It provides the anti-loop feature that is needed to ensure that the message will be seen once by all Global Brokers.
It remains the same throughout the lifetime of the message in the WIS2 ecosystem.

The message identifier is set to a new value by Global Cache services when they publish their modified message for accessing the original core
data from the cache. The <<data_id>> is retained to ensure traceability and consistency of the same resource.

[source,json]
----
"id": "31e9d66a-cd83-4174-9429-b932f1abe1be"
----

include::../requirements/core/REQ_id.adoc[]

==== Version

The ``version`` property provides the version of WNM that the message conforms to.

include::../requirements/core/REQ_version.adoc[]

==== Type

The ``type`` property is a fixed value denoting the record as a GeoJSON Feature.

include::../requirements/core/REQ_type.adoc[]

==== Geometry

RFC7946 defines 7 types of geometry: ``Point``, ``MultiPoint``, ``LineString``, ``MultiLineString``, ``Polygon``, ``MultiPolygon``, and ``GeometryCollection``.
It has been decided to restrict those types to only two: ``Point`` and ``Polygon``.
It must be noted that the geometry key is mandatory in GeoJSON but can be of type ``null``.

include::../requirements/core/REQ_geometry.adoc[]
include::../recommendations/core/PER_geometry.adoc[]

.Example: Point
[source,json]
----
{
  ...
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.146255135536194,
      46.223296618227444
    ]
  }
  ...
}
----

.Example: Point with elevation
[source,json]
----
{
  ...
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.146255135536194,
      46.223296618227444,
      392
    ]
  }
  ...
}
----

.Example: Polygon
[source,json]
----
{
  ...
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-7.75,40.43],
      [-7.75,78.46],
      [71.91,78.46],
      [71.91,40.43],
      [-7.75,40.43]
    ]]
  }
  ...
}
----

.Example: null

[source,json]
----
{
  ...
  "geometry": null
  ...
}
----

==== Properties

===== pubtime

The ``pubtime`` property identifies the date/time of when the file was posted/published, in RFC3339 format, in
the UTC timezone (``Z``). The publication date/time is critical for subscribers to prevent message loss in
providing awareness of how far behind the publisher they may be).  ``pubtime`` is also valuable for change
detection as part of updates and deletion notifications.  Ensuring ``pubtime`` is properly managed for updates
and deletions is important for data and metadata download workflows (an out of date ``pubtime`` can lead
to errors for clients when managing updates or deletions in their local copies of data).

[source,json]
----
"properties": {
  ...
  "pubtime": "2022-03-20T04:50:18.314854383Z"
  ...
}
----

include::../requirements/core/REQ_pubtime.adoc[]
include::../recommendations/core/REC_pubtime.adoc[]

[[data_id]]
===== data_id

The ``data_id`` property uniquely identifies the data as defined by the data producer. A data producer may use
the identification scheme of their choice in support of uniquely identifying data described by the notification.

include::../requirements/core/REQ_data_id.adoc[]
include::../recommendations/core/REC_data_id.adoc[]
include::../recommendations/core/PER_data_id.adoc[]

[source,json]
----
"properties": {
  ...
  "data_id": "org1/datasets/123/data/UANT01_CWAO_200445___15103.bufr4"
  ...
}
----

[[metadata_id]]
===== metadata_id

The ``metadata_id`` property uniquely identifies the associated discovery metadata record to which the notification applies to. This element is an important linkage between a dataset discovery metadata record and its data notifications, allowing a subscriber to consult additional documentation of the dataset, including any access control applied to the data.

include::../recommendations/core/REC_metadata_id.adoc[]

[source,json]
----
"properties": {
  ...
  "metadata_id": "urn:x-wmo:md:can:eccc-msc:observations.swob"

  ...
}
----

===== Temporal description (datetime, start_datetime, end_datetime)

The ``datetime`` property identifies the date and time of the data (e.g. date of measurement, for observation data), in RFC3339 format, in the UTC timezone (``Z``).

The ``start_datetime`` and ``end_datetime`` properties identify a temporal extent (e.g. start/end times for an NWP forecasting period), in RFC3339 format, in the UTC timezone (``Z``). 

A ``null`` value can also be used if no temporal description of the data can be derived as part of generating the message.

include::../requirements/core/REQ_temporal.adoc[]

.Example: Temporal instant
[source,json]
----
"properties": {
  ...
  "datetime": "2022-03-20T04:45:00Z"
  ...
}
----

.Example: Temporal extent
[source,json]
----
"properties": {
  ...
  "start_datetime": "2022-03-20T04:45:00Z",
  "end_datetime": "2022-03-22T04:45:00Z"
  ...
}
----

.Example: No temporal description
[source,json]
----
"properties": {
  "datetime": null,
  ...
}
----

===== Cache

For core data, the data in a notification's canonical link is always cached by Global Cache services by default.

There exist scenarios where core data may continue to be hosted by the data producer. Examples include (but are not limited to):

* size: the size of the data is very large and not suitable for storage to the Global Cache
* download metrics: data producers may wish to keep data access isolated to their facilities in support of their own download metrics
  and reporting

A data producer can use the ``properties.cache`` value to signify Global Cache services to not cache their data granule and keep any
canonical links unmodified.

The data notification is always published by the Global Cache regardless of this value to the `cache` topic.

.Example: Specifying data not to be cached
[source,json]
----
"properties": {
  "cache": false,
  ...
}
----

include::../recommendations/core/PER_cache.adoc[]


===== Integrity

For data verification, it is suggested (but not mandatory) to include data integrity information via the ``integrity`` property.  Providing this information will allow data consumers to ensure
that a given data granule has not been corrupted during download.

The ``method`` property provides a format of the hashing method used to enable integrity check of the data. Acceptable values
are ``sha256``, ``sha384``, ``sha512``, ``sha3-256``, ``sha3-384``, and ``sha3-512``.  ``sha512`` is preferred.

The ``value`` property provides the result of the hashing method, base64 encoded.

include::../recommendations/core/REC_integrity.adoc[]

[source,json]
----
"properties": {
  ...
  "integrity": {
    "method": "sha512",
    "value": "CPvTLiOfYRgfL3YNF/KKElwamwvLQwnzd96VnF2WoYuuH+hVIbwFSPQHHd/qa/fNVUBckviC5/HZs3Nx2jXEsA=="
  }
  ...
}
----

===== Content

For data granules with sizes smaller than 4096 bytes, the ``content`` property allows for including the data in the message. The ``content`` property provides an additional inline data access capability, in addition to a canonical link of the message.

The ``encoding`` property provides the character encoding of the data (fixed to UTF-8 or Base64).

The ``value`` property provides the data in the in accordance to the ``encoding`` property.

The ``size`` property provides the size, in bytes, of the data in accordance to the ``encoding`` property. The value must be below 4096. Global Brokers may discard messages for where inline data sizes are greater than 4096 bytes.

The limit takes into account the used data encoding. That is, if the data is compressed with gzip (``properties.content.encoding="gzip"``), the compressed size must be less than 4096 bytes.

include::../requirements/core/REQ_content.adoc[]
include::../recommendations/core/REC_content.adoc[]
include::../recommendations/core/PER_content.adoc[]

[source,json]
----
"properties": {
  ...
  "content": {
    "encoding": "utf-8",
    "value": "encoded bytes from the file",
    "size": 457
  }
  ...
}
----

===== Additional properties

A WIS2 Notification Message can be extended as required for organizational purposes by adding properties (of any type) in the message. Additional properties do not break compliance to this specification.

include::../recommendations/core/PER_additional_properties.adoc[]

[source,json]
----
"properties": {
  ...
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

==== Links

The ``links`` array consists of one or more objects providing URLs to access data.

Each link object provides:

* an ``href`` property with a fully qualified link to access the data in a secure manner
* a ``rel`` property providing an IANA link relation footnote:[https://www.iana.org/assignments/link-relations/link-relations.xhtml] describing the relationship between the link and the message
* a ``type`` property providing the media type of the data
* a ``length`` property providing the length (in bytes) indicating the size of the data in the response when downloading the link.

Links are used to communicate new or updated data or metadata notifications.  Links can also communicate when data or metadata has been deleted or invalidated.  Note that this differs from rolling data archives (which can be described accordingly in dataset discovery metadata, for example).

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_links.adoc[]
include::../recommendations/core/PER_links.adoc[]

.Example: Canonical link
[source,json]
----
"links": [{
  "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
  "rel": "canonical",
  "type": "application/x-bufr"
}]
----

.Example: Multiple links
[source,json]
----
"links": [{
  "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
  "rel": "canonical",
  "type": "application/x-bufr"
}, {
  "href": "https://example.org/oapi/collections/my-dataset/items/my-data-granule",
  "rel": "item",
  "type": "application/json"
}]
----
