
== Appendix E: WIS2 Notification Message

The WIS2 Notification Message (WNM) is an extension of the OGC API - Features standard  and shall be encoded in GeoJSON. The normative provisions in this standard are denoted by the base URI (``http://wis.wmo.int/spec/wnm/1``) and requirements are denoted by partial URIs relative to this base. Property names, values and examples are represented with ``shaded`` text in this document.

:sectnums!:
=== 1. Requirements Class "Core"

include::../requirements/requirements_class_core.adoc[]

==== 1.1 Overview

The table below provides an overview of the set of properties that may be included in a WNM.

.WNM core properties
|===
|Property|Requirement|Description

|``id``
|**required**
|A universally unique identifier of the message (see <<_1_4_identifier>>)

|``type``
|**required**
|A fixed value denoting the record as a GeoJSON ``Feature`` (see <<_1_3_geojson_compliance>>)


|``conformsTo``
|**required** (one of ``conformsTo`` or ``version``)
|The version of WNM associated that the record conforms to (see <<_1_5_conformance>>.

|``version``
|**required** (one of ``conformsTo`` or ``version``)
|*DEPRECATED.*  Please use ``conformsTo`` (see <<_1_5_conformance>>)

|``geometry``
|**required**
|Geospatial location associated with the data or metadata (see <<_1_7_geometry>>)

|``properties.pubtime``
|**required**
|The date and time of when the notification was published, in RFC3339 format (see <<_1_8_properties_publication_time>>), UTC

|``properties.data_id``
|**required**
|Unique identifier of the data as defined by the data producer (see <<_1_9_properties_data_identification>>)

|``properties.metadata_id``
|optional
|Identifier for associated discovery metadata record to which the notification applies (see <<_1_10_properties_metadata_identification>>)

|``properties.producer``
|optional
|Identifies the provider that initially captured and processed the source data, in support of data distribution on behalf of other Members (see <<_1_11_properties_producer>>)

|``properties.datetime``
|optional
|Identifies the reference date and time of the data instance to which the notification is relayed, in RFC3339 format (see <<_1_12_properties_temporal_description>>), UTC

|``properties.start_datetime``
|optional
|Identifies the start date and time of the data being published, in RFC3339 format (see <<_1_12_properties_temporal_description>>)

|``properties.end_datetime``
|optional
|Identifies the end date and time of the data being published, in RFC3339 format (see <<_1_12_properties_temporal_description>>)

|``properties.cache``
|optional
|Indicates whether the data in the notification should be cached (if not specified, the default value is `true`) (see <<_1_13_properties_cache>>)

|``properties.integrity``
|optional
|Specifies a checksum to be applied to the data to ensure that the download is accurate (see <<_1_14_properties_integrity>>)

|``properties.content``
|optional
|Used to embed small products inline within the message (see <<_1_15_properties_content>>)

|``links``
|**required**
|Online linkages for data retrieval or additional resources associated with the dataset (see <<_1_16_links>>)

|===

==== 1.2 Message size

The WIS2 Notification Message allows for the transmission of messages in a compact manner and includes the ability to embed content inline as required (see <<Properties / Content>>).

include::../requirements/core/REQ_message_size.adoc[]

==== 1.3 GeoJSON compliance

The WIS2 Notification Message schema is based on _GeoJSON_ (RFC7946) and its associated information model.  Compliant messages are therefore compliant with _GeoJSON_.

include::../requirements/core/REQ_validation.adoc[]

==== 1.4 Identifier

A universally unique identifier of the message using the UUID standard (RFC4122). The identifier is generated by the originator of the message.
It provides the anti-loop feature that is needed to ensure that the message will be seen once by all Global Brokers.
It remains the same throughout the lifetime of the message in the WIS2 ecosystem.

The <<data_id>> is retained to ensure traceability and consistency of the same resource.

[source,json]
----
"id": "31e9d66a-cd83-4174-9429-b932f1abe1be"
----

include::../requirements/core/REQ_id.adoc[]

==== 1.5 Conformance

The `+conformsTo+` property to identifies the version of the WNM standard that the notification conforms to. Conformance identification is valuable for version
detection and handling of content.

.Example

[source,json]
----
"conformsTo": [
  "http://wis.wmo.int/spec/wnm/1/conf/core"
]
----

include::../requirements/core/REQ_conformance.adoc[]

==== 1.6 Version

*DEPRECATED.  Please use `conformsTo`.*

The ``version`` property provides the version of WNM that the message conforms to.

include::../requirements/core/REQ_version.adoc[]

==== 1.7 Geometry

The type of geometry in a notification message may be ``Point`` or ``Polygon``. It can also be type ``null`` if the geometry cannot be derived.

.Example. Point
[source,json]
----
{
  ...
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.146255135536194,
      46.223296618227444
    ]
  }
  ...
}
----

.Example. Point with elevation
[source,json]
----
{
  ...
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.146255135536194,
      46.223296618227444,
      392
    ]
  }
  ...
}
----

.Example. Polygon
[source,json]
----
{
  ...
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-7.75,40.43],
      [-7.75,78.46],
      [71.91,78.46],
      [71.91,40.43],
      [-7.75,40.43]
    ]]
  }
  ...
}
----

.Example. null

[source,json]
----
{
  ...
  "geometry": null
  ...
}
----

include::../requirements/core/REQ_geometry.adoc[]
include::../recommendations/core/PER_geometry.adoc[]

==== 1.8 Properties / Publication time

The ``pubtime`` property identifies the date/time when the notification was first posted or published by the originator. The date/time is encoded in RFC3339 format with the Coordinated Universal Time (UTC) timezone (``Z``). 

The publication date/time is critical for subscribers to prevent message loss in providing awareness of how far behind the publisher they may be.  

The ``pubtime`` property is also valuable for change detection as part of updates and deletion notifications.

Ensuring ``pubtime`` is properly managed for updates and deletions is important for data and metadata download workflows.
For example, an out-of-date ``pubtime`` can lead to errors for clients when managing updates or deletions in their local copies of data.
An update with newer ``pubtime`` and identical ``datetime`` indicates a newer version of the data or metadata.

[source,json]
----
"properties": {
  ...
  "pubtime": "2022-03-20T04:50:18.314854383Z"
  ...
}
----

include::../requirements/core/REQ_pubtime.adoc[]

==== 1.9 Properties / Data identification

The ``data_id`` property uniquely identifies the data described by the notification and is defined by the data producer. A data producer may use an identification scheme of their choice.

Example.

[source,json]
----
"properties": {
  ...
  "data_id": "wis2/ma-marocmeteo/data/core/weather/surface-based-observations/synop/WIGOS_0-504-1-60288_20240210T130000"
  ...
}
----

include::../requirements/core/REQ_data_id.adoc[]
include::../recommendations/core/REC_data_id.adoc[]
include::../recommendations/core/PER_data_id.adoc[]


==== 1.10 Properties / Metadata identification

The ``metadata_id`` property uniquely identifies the associated discovery metadata record. This property is an important linkage between a WCMP2 dataset discovery metadata record and the related data notifications. The inclusion of this property allows a subscriber to consult additional documentation of the dataset and understand the access control applied to the data.

Example.

[source,json]
----
"properties": {
  ...
  "metadata_id": "urn:wmo:md:ca-eccc-msc:observations.swob"
  ...
}
----

include::../recommendations/core/REC_metadata_id.adoc[]

==== 1.11 Properties / Producer

The ``producer`` property identifies the provider that initially captured and processed the source data, in support of data distribution on behalf of other Members.

[source,json]
----
"properties": {
  ...
  "producer": "fra"
  ...
}
----

include::../recommendations/core/REC_producer.adoc[]

==== 1.12 Properties / Temporal description 

The ``datetime`` property identifies the date and time of the data (for example, when a measurement was observed).
When a data or metadata is updated or deleted, this value should identify the original data or metadata, which can be significantly different from the current time.

The ``start_datetime`` and ``end_datetime`` properties identify a temporal extent (for example, the start and end times of an NWP forecasting period). All dates and times are encoded in RFC3339 format with the UTC timezone (``Z``). A ``null`` value can also be used if a temporal description of the data cannot be derived.

.Example. Temporal instant
[source,json]
----
"properties": {
  ...
  "datetime": "2022-03-20T04:45:00Z"
  ...
}
----

.Example. Temporal extent
[source,json]
----
"properties": {
  ...
  "start_datetime": "2022-03-20T04:45:00Z",
  "end_datetime": "2022-03-22T04:45:00Z"
  ...
}
----

.Example. No temporal description
[source,json]
----
"properties": {
  "datetime": null,
  ...
}
----

include::../requirements/core/REQ_temporal.adoc[]

==== 1.13 Properties / Cache

Core data, by default, is cached by Global Cache services as described in the _Guide to WIS_, Volume II.

However, a data producer can use the ``properties.cache`` value to request Global Cache services to not cache their ``core`` data granule.

.Example. Specifying data not to be cached
[source,json]
----
"properties": {
  "cache": false,
  ...
}
----

include::../recommendations/core/PER_cache.adoc[]

==== 1.14 Properties / Integrity

For data verification, it is recommended to include data integrity information via the ``integrity`` property.  Providing this information will allow data consumers to ensure
that a given data granule has not been corrupted during download.

The ``method`` property provides a format of the hashing method used to enable an integrity check of the data. The preferred values
are ``sha256``, ``sha384``, ``sha512``, ``sha3-256``, ``sha3-384``, and ``sha3-512``.

The ``value`` property provides the result of the hashing method in base64 encoding.

Example.

[source,json]
----
"properties": {
  ...
  "integrity": {
    "method": "sha512",
    "value": "CPvTLiOfYRgfL3YNF/KKElwamwvLQwnzd96VnF2WoYuuH+hVIbwFSPQHHd/qa/fNVUBckviC5/HZs3Nx2jXEsA=="
  }
  ...
}
----

include::../recommendations/core/REC_integrity.adoc[]

==== 1.15 Properties / Content

The ``content`` property allows for the inclusion of data in the notification message when the length of the data, once encoded, is smaller than 4096 bytes.

The ``encoding`` property provides the character encoding of the data (``UTF-8``, ``Base64``, or ``gzip``), the ``gzip`` encoding means that the data are compressed using algorithm defined in link:https://datatracker.ietf.org/doc/html/rfc1952[RFC1952] and consequently converted to text using Base64 encoding.

The ``value`` property provides the data in accordance with the ``encoding`` property.

The ``size`` property provides the size, in bytes, of the data in its original unencoded form, therefore this value shall not be directly compared with the size limit.

Example. 

[source,json]
----
"properties": {
  ...
  "content": {
    "encoding": "utf-8",
    "value": "encoded bytes from the file",
    "size": 457
  }
  ...
}
----

include::../requirements/core/REQ_content.adoc[]
include::../recommendations/core/REC_content.adoc[]
include::../recommendations/core/PER_content.adoc[]

==== 1.16 Links

The ``links`` array property consists of one or more objects providing URLs to access data.

Each link object provides:

* An ``href`` property with a fully qualified link to access the data
* A ``rel`` property providing an link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relation] or link:http://codes.wmo.int/wis/link-type[WIS link type] describing the relationship between the link and the message
* A ``type`` property providing the media type of the data
* A ``length`` property providing the length (in bytes) indicating the size of the data
* A ``security`` property providing a description of the access control mechanism applied (for example, recommended data with restrictions).
 
Links are used to communicate new data or metadata notifications.  Links can also communicate when data or metadata has been deleted or invalidated.  

.Example. Canonical link
[source,json]
----
"links": [{
  "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
  "rel": "canonical",
  "type": "application/bufr"
}]
----

.Example. Multiple links
[source,json]
----
"links": [{
  "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
  "rel": "canonical",
  "type": "application/x-bufr"
}, {
  "href": "https://example.org/oapi/collections/my-dataset/items/my-data-granule",
  "rel": "item",
  "type": "application/json"
}]
----

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_links.adoc[]
include::../recommendations/core/PER_links.adoc[]

===== 1.16.1 Access control

For recommended data, WNM links may also provide links to resources that implement access control in support of authentication and authorization. In secure data use cases, a user needs to be able to detect access controlled data as part of data discovery and evaluation. The example demonstrates how to express access control using HTTP basic authentication for a given data access service.

.Example. Access controlled link
[source,json]
----
"links": [{
  "rel": "data",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "default": {
      "type": "http",
      "scheme": "basic",
      "description": "Please contact the data provider for accessing this secured resource."
    }
  }
}]
----

==== 1.17 Additional properties

A WIS2 Notification Message can be extended as required for organizational purposes by adding properties (of any type) in the message. Additional properties do not break compliance with this specification.

Example.

[source,json]
----
"properties": {
  ...
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

include::../recommendations/core/PER_additional_properties.adoc[]

== 2. WIS2 notification message resources
=== 2.1 WMO Codes Registry
•	http://codes.wmo.int/wis/link-type 

=== 2.2	WMO schemas server
Validation, examples and other resources are published at https://schemas.wmo.int/wnm.
