== The WIS2 Notification Message Encoding

A WIS2 Notification Message (WNM) provides descriptive information about data or metadata made available through WIS 2.0. The standard notification message format ensures that the WIS2 ecosystem (data publisher, data user, and global services) is a robust, effective, and unified data exchange platform for weather, climate, and water.

WIS2 Notification Message documents are provided as MQP payloads by WIS2 nodes, Global Broker services, as well as Replay API services.

A WNM provides notification metadata about data or metadata published to WIS2, including when the data was published, its spatial and temporal characteristics, and where to access and download.

WIS2 Notification Message is an extension of the OGC API - Features standard [3] and shall be encoded in GeoJSON (RFC7946 [4]).

=== Conformance Class "Core"

==== Overview

This Core Conformance Class provides requirements for a WIS2 Notification Message.

include::../requirements/requirements_class_core.adoc[]

The table below provides an overview of the set of properties that may be included in a WNM.

.WNM core properties
|===
|Property|Requirement|Description

|``id``
|**required**
|A universally unique identifier of the message (see <<_identifier>>)

|``type``
|**required**
|A fixed value denoting the record as a GeoJSON ``Feature`` (see <<_geojson_compliance>>)

|``version``
|**required**
|Version of message specification (see <<_version>>)

|``geometry``
|**required**
|Geospatial location associated with the data or metadata, in a geographic coordinate reference system (see <<_geometry>>)

|``properties.pubtime``
|**required**
|The date and time of when the notification was published, in RFC3339 format (see <<_properties_publication_time>>)

|``properties.data_id``
|**optional**
|Unique identifier of the data as defined by the data producer (see <<data_id>>)

|``properties.metadata_id``
|**optional**
|Identifier for associated discovery metadata record to which the notification applies (see <<metadata_id>>)

|``properties.producer``
|**optional**
|Identifies the provider that initially captured and processed the source data, in support of data distribution on behalf of other Members (see <<_properties_producer>>)

|``properties.datetime``
|**optional**
|Identifies the date and time of the data being published, in RFC3339 format (see <<_properties_temporal_description>>)

|``properties.start_datetime``
|**optional**
|Identifies the start date and time of the data being published, in RFC3339 format (see <<_properties_temporal_description>>)

|``properties.end_datetime``
|**optional**
|Identifies the end date and time of the data being published, in RFC3339 format (see <<_properties_temporal_description>>)

|``properties.cache``
|**optional**
|Indicates whether the data in the notification should be cached (if not specified, the default value is `true`) (see <<_properties_cache>>)

|``properties.integrity``
|**optional**
|Specifies a checksum to be applied to the data to ensure that the download is accurate (see <<_properties_integrity>>)

|``properties.content``
|**optional**
|Used to embed small products inline within the message (see <<_properties_content>>)

|``links``
|**required**
|Online linkages for data retrieval or additional resources associated with the dataset (see <<_links>>)

|===


==== Message size

The WIS2 Notification Message allows for the transmission of messages in a compact manner and includes the ability to embed content inline as required (see <<Properties / Content>>).

include::../requirements/core/REQ_message_size.adoc[]

==== GeoJSON compliance

The WIS2 Notification Message schema is based on _GeoJSON_ (RFC7946) and its associated information model.  Compliant messages are therefore compliant with _GeoJSON_.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

A universally unique identifier of the message using the UUID standard (RFC4122). The identifier is generated by the originator of the message.
It provides the anti-loop feature that is needed to ensure that the message will be seen once by all Global Brokers.
It remains the same throughout the lifetime of the message in the WIS2 ecosystem.

The <<data_id>> is retained to ensure traceability and consistency of the same resource.

[source,json]
----
"id": "31e9d66a-cd83-4174-9429-b932f1abe1be"
----

include::../requirements/core/REQ_id.adoc[]

==== Version

The ``version`` property provides the version of WNM that the message conforms to.

include::../requirements/core/REQ_version.adoc[]

==== Type

The ``type`` property is a fixed value denoting the record as a GeoJSON Feature.

include::../requirements/core/REQ_type.adoc[]

==== Geometry

The type of geometry in a notification message may be ``Point`` or ``Polygon``. It can also be type ``null`` if the geometry cannot be derived.

include::../requirements/core/REQ_geometry.adoc[]
include::../recommendations/core/PER_geometry.adoc[]

.Example: Point
[source,json]
----
{
  ...
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.146255135536194,
      46.223296618227444
    ]
  }
  ...
}
----

.Example: Point with elevation
[source,json]
----
{
  ...
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.146255135536194,
      46.223296618227444,
      392
    ]
  }
  ...
}
----

.Example: Polygon
[source,json]
----
{
  ...
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-7.75,40.43],
      [-7.75,78.46],
      [71.91,78.46],
      [71.91,40.43],
      [-7.75,40.43]
    ]]
  }
  ...
}
----

.Example: null

[source,json]
----
{
  ...
  "geometry": null
  ...
}
----

==== Properties / Publication Time

The ``pubtime`` property identifies the date/time when the notification was first posted or published. The date/time is encoded in RFC3339 format with the UTC timezone (``Z``). 

The publication date/time is critical for subscribers to prevent message loss in providing awareness of how far behind the publisher they may be.  

The ``pubtime`` property is also valuable for change detection as part of updates and deletion notifications.  

Ensuring ``pubtime`` is properly managed for updates and deletions is important for data and metadata download workflows. For example, an out-of-date ``pubtime`` can lead to errors for clients when managing updates or deletions in their local copies of data.

[source,json]
----
"properties": {
  ...
  "pubtime": "2022-03-20T04:50:18.314854383Z"
  ...
}
----

include::../requirements/core/REQ_pubtime.adoc[]
include::../recommendations/core/REC_pubtime.adoc[]

[[data_id]]
==== Properties / Data Identification

The ``data_id`` property uniquely identifies the data described by the notification and is defined by the data producer. A data producer may use an identification scheme of their choice.

include::../requirements/core/REQ_data_id.adoc[]
include::../recommendations/core/REC_data_id.adoc[]
include::../recommendations/core/PER_data_id.adoc[]

[source,json]
----
"properties": {
  ...
  "data_id": "org1/datasets/123/data/UANT01_CWAO_200445___15103.bufr4"
  ...
}
----

[[metadata_id]]
==== Properties / Metadata identification

The ``metadata_id`` property uniquely identifies the associated discovery metadata record. This property is an important linkage between a WCMP2 dataset discovery metadata record and the related data notifications. The inclusion of this property allows a subscriber to consult additional documentation of the dataset and understand the access control applied to the data.

include::../recommendations/core/REC_metadata_id.adoc[]

[source,json]
----
"properties": {
  ...
  "metadata_id": "urn:x-wmo:md:can:eccc-msc:observations.swob"
  ...
}
----

==== Properties / Producer

The ``producer`` property identifies the provider that initially captured and processed the source data, in support data distribution on behalf of other Members.

[source,json]
----
"properties": {
  ...
  "producer": "fra"
  ...
}
----

include::../recommendations/core/REC_producer.adoc[]

==== Properties / Temporal description 

The ``datetime`` property identifies the date and time of the data (for example, when a measurement was observed). 

The ``start_datetime`` and ``end_datetime`` properties identify a temporal extent (for example, the start and end times of an NWP forecasting period).

All dates and times are encoded in RFC3339 format with the UTC timezone (``Z``). 

A ``null`` value can also be used if a temporal description of the data cannot be derived.

include::../requirements/core/REQ_temporal.adoc[]

.Example: Temporal instant
[source,json]
----
"properties": {
  ...
  "datetime": "2022-03-20T04:45:00Z"
  ...
}
----

.Example: Temporal extent
[source,json]
----
"properties": {
  ...
  "start_datetime": "2022-03-20T04:45:00Z",
  "end_datetime": "2022-03-22T04:45:00Z"
  ...
}
----

.Example: No temporal description
[source,json]
----
"properties": {
  "datetime": null,
  ...
}
----

==== Properties / Cache

All core data, by default, is cached by Global Cache services.

However, a data producer can use the ``properties.cache`` value to request Global Cache services to not cache their ``core`` data granule.

.Example: Specifying data not to be cached
[source,json]
----
"properties": {
  "cache": false,
  ...
}
----

include::../recommendations/core/PER_cache.adoc[]


==== Properties / Integrity

For data verification, it is recommended to include data integrity information via the ``integrity`` property.  Providing this information will allow data consumers to ensure
that a given data granule has not been corrupted during download.

The ``method`` property provides a format of the hashing method used to enable an integrity check of the data. The preferred values
are ``sha256``, ``sha384``, ``sha512``, ``sha3-256``, ``sha3-384``, and ``sha3-512``.  ``sha512``.

The ``value`` property provides the result of the hashing method in base64 encoding.

include::../recommendations/core/REC_integrity.adoc[]

[source,json]
----
"properties": {
  ...
  "integrity": {
    "method": "sha512",
    "value": "CPvTLiOfYRgfL3YNF/KKElwamwvLQwnzd96VnF2WoYuuH+hVIbwFSPQHHd/qa/fNVUBckviC5/HZs3Nx2jXEsA=="
  }
  ...
}
----

==== Properties / Content

The ``content`` property allows for the inclusion of data in the notification message when the data is smaller than 4096 bytes. 

The ``encoding`` property provides the character encoding of the data (``UTF-8``, ``Base64``, or ``gzip``).

The ``value`` property provides the data in accordance with the ``encoding`` property.

The ``size`` property provides the size, in bytes, of the data in accordance with the ``encoding`` property. The value must be below 4096. Global Brokers may discard messages where inline data sizes are greater than 4096 bytes.

The limit takes into account the data encoding. That is if the data are compressed with gzip, the compressed size must be less than 4096 bytes. 

include::../requirements/core/REQ_content.adoc[]
include::../recommendations/core/REC_content.adoc[]
include::../recommendations/core/PER_content.adoc[]

[source,json]
----
"properties": {
  ...
  "content": {
    "encoding": "utf-8",
    "value": "encoded bytes from the file",
    "size": 457
  }
  ...
}
----

==== Links

The ``links`` array property consists of one or more objects providing URLs to access data.

Each link object provides:

* an ``href`` property with a fully qualified link to access the data
* a ``rel`` property providing an IANA link relation footnote:[https://www.iana.org/assignments/link-relations/link-relations.xhtml] describing the relationship between the link and the message
* a ``type`` property providing the media type of the data
* a ``length`` property providing the length (in bytes) indicating the size of the data.
 
Links are used to communicate new data or metadata notifications.  Links can also communicate when data or metadata has been deleted or invalidated.  

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_links.adoc[]
include::../recommendations/core/PER_links.adoc[]

.Example: Canonical link
[source,json]
----
"links": [{
  "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
  "rel": "canonical",
  "type": "application/x-bufr"
}]
----

.Example: Multiple links
[source,json]
----
"links": [{
  "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
  "rel": "canonical",
  "type": "application/x-bufr"
}, {
  "href": "https://example.org/oapi/collections/my-dataset/items/my-data-granule",
  "rel": "item",
  "type": "application/json"
}]
----

==== Additional properties

A WIS2 Notification Message can be extended as required for organizational purposes by adding properties (of any type) in the message. Additional properties do not break compliance with this specification.

include::../recommendations/core/PER_additional_properties.adoc[]

[source,json]
----
"properties": {
  ...
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----
