name: validate schema and examples

on:
  push:
    paths:
      - '**.json'   
      - '**.yaml'   
  pull_request:
    paths:
      - '**.json'   
      - '**.yaml'   

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r tools/requirements.txt
    - name: Validate schema
      run: |
        python3 tools/validate.py schema schemas/notificationMessageGeoJSON.yaml
    - name: Validate examples
      run: |
        python3 tools/validate.py instance schemas/notificationMessageGeoJSON.yaml examples/example1.json
        python3 tools/validate.py instance schemas/notificationMessageGeoJSON.yaml examples/example2.json
        python3 tools/validate.py instance schemas/notificationMessageGeoJSON.yaml examples/example3.json
    - name: Run flake8 against script(s)
      run: |
        flake8 tools/validate.py
